### ISSUE TITLE
Sorting icons are hidden in data.frame previews

### ISSUE THREAD

**Issue by Darxor** [gadenbuie/rsthemes#25]
Currently when rsthemes are applied they hide sorting icons (little arrows, see attached screenshot below) present in the header of data.frame preview. Sorting itself is functional, but there is no way to tell its direction.

![image](https://user-images.githubusercontent.com/1351765/81011068-fadc4b80-8e5f-11ea-8a71-398b9c3863cb.png)

It seems, that its not intentional and can be easily fixed by replacing `background` property with `background-color` for `.dataTables_wrapper thead th` selector in respective templates

https://github.com/gadenbuie/rsthemes/blob/60f0de27b97ad30be8cfba772b81c6fb88c232b9/inst/templates/rstudio/_rstudio-light.scss#L357-L360

https://github.com/gadenbuie/rsthemes/blob/60f0de27b97ad30be8cfba772b81c6fb88c232b9/inst/templates/rstudio/_rstudio-dark.scss#L325-L328

**Comment by gadenbuie** [comment]
Thanks for the report and research!
