### ISSUE TITLE
Custom colors for rainbow parentheses

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/rsthemes#28]
- [x] ensure current themes aren’t broken
- [x] add partial for parens
- [x] maybe customize paren colors for one or two themes

https://github.com/rstudio/rstudio/pull/7027

**Comment by adamconroy** [comment]
Thanks Gaden. I tried to pick defaults that looked ok in most Light/Dark themes but there will definitely be some exceptions. The yellow/orange-ish backgrounds especially will have some trouble with the warmer default paren colors. My dream down the road would be to add a custom UI for easy user configuration (with save-able presets) but unfortunately without the correct widgets already in the program it was out of scope for this feature. Feel free to bug me if anything doesn't work quite right or if you have any questions.

**Comment by gadenbuie** [comment]
Thanks @adamconroy, I'm really excited for this feature!
