### ISSUE TITLE
Highlighting on One Dark theme

### ISSUE THREAD

**Issue by Tacfarinas** [gadenbuie/rsthemes#29]
The highlighting is dark on the One Dark theme. I attempted to edit the CSS file in Devtools. However I am unable to save the changes. Any help would be appreciated.
```
.ace_marker-layer .ace_selection {
    background: #996bbb;
}
```

**Comment by gadenbuie** [comment]
The easiest way to tweak the theme would be to copy the `one-dark.rstheme` from the package, change the lines you want, give it a new name, and then install your new tweaked theme.

```r
one_dark_pkg <- system.file("themes", "one-dark.rstheme", package = "rsthemes")
file.copy(one_dark_pkg, "my-one-dark.rstheme")
file.edit("my-one-dark.rstheme")
# change the first line to something like /* rs-theme-name: One Dark {mine} */
# tweak the CSS you want in the file and save
rstudioapi::addTheme("my-one-dark.rstheme", apply = TRUE)
```

**Comment by Tacfarinas** [comment]
Thanks!
