### ISSUE TITLE
Invisible code in snippets with "Night Owl" and "Horizon Dark"

### ISSUE THREAD

**Issue by etiennebacher** [gadenbuie/rsthemes#37]
The code for snippets is invisible with "Night Owl" and "Horizon Dark".

Reproduce: 
* Tools > Global Options > Code > Edit Snippets 
* RStudio 1.3.1093

Thanks for the nice package :)

**Comment by gadenbuie** [comment]
Thanks for letting me know! After a quick look this is going to take a bit of hacking, but the CSS rule that's causing problems is here: https://github.com/gadenbuie/rsthemes/blob/927d529f0bd67ef4a2185edde4e496ad4b6c6c6f/inst/templates/rstudio/_dialog-options.scss#L35
