### ISSUE TITLE
Flat White theme bugs

### ISSUE THREAD

**Issue by MikeJohnPage** [gadenbuie/rsthemes#48]
In the 'Global Options' pane, the 'Code' tab contains a bug in that all boxes contain a tick, with those options you have selected containing two ticks:

<img width="527" alt="Screenshot 2020-12-21 at 17 58 59" src="https://user-images.githubusercontent.com/38110953/102802187-92be8380-43b6-11eb-8727-7c3f467a3c1b.png">

The code snippets pain also fails to show snippets:

<img width="914" alt="Screenshot 2020-12-21 at 17 59 09" src="https://user-images.githubusercontent.com/38110953/102802352-c8fc0300-43b6-11eb-9b6c-599d7ac6f858.png">

Thanks for all your work on this package (and particuraly this theme), you have done an amazing job.

**Comment by gadenbuie** [comment]
Thanks for the report! Can you verify that you're using the latest version of the themes? I think I fixed the code display in the snippets dialog and possibly the checkboxes. But I may have been testing with the dark themes and missed that my fixes didn't work for Flat White.

**Comment by MikeJohnPage** [comment]
No, I wasn't. I just installed the latest version and that indeed fixed it. Thanks 👍
