### ISSUE TITLE
error 404 when installing

### ISSUE THREAD

**Issue by verajosemanuel** [gadenbuie/rsthemes#50]
> devtools::install_github("gadenbuie/rsthemes")
Error: HTTP error 404.
  No commit found for the ref master

  Rate limit remaining: 56/60
  Rate limit reset at: 2020-12-23 18:22:40 UTC

**Comment by gadenbuie** [comment]
I recently switched the default branch in this repo from `master` to `main`, and older versions of devtools or remotes use `master` by default. You can either update devtools or explicitly specify the branch to install by using `"gadenbuie/rsthemes@main"`.

**Comment by verajosemanuel** [comment]
It worked! Thanks
