### ISSUE TITLE
Fix check boxes in Global options menus

### ISSUE THREAD

**Issue by CLRafaelR** [gadenbuie/rsthemes#51]
# Problem

Similar to #39.  The ballot boxes in Global Options are automatically ticked and untickable in "Night Owl" and "Horizon Dark". I suspect that the problem may affect every theme whose "Options" window uses different theme from the default/original "Options" window theme. 

For instance, "Night Owl"'s "Options" uses a navy window unlike the default, white window, as demonstrated in the following screen capture. Actually I untick "Soft-wrap R source files", "Continue comment when inserting new line" and "Focus console after executing from source", but, as shown in the picture, the menu window still shows ☑️ on these options. 

![image](https://user-images.githubusercontent.com/42314553/103456777-baa9d180-4d3c-11eb-8686-a17803e8499b.png)

In "GitHub" theme, however, the unticked options are correctly marked with a blank box, ☐. I think this is because the theme inherits the default window.

![image](https://user-images.githubusercontent.com/42314553/103457028-fd6ca900-4d3e-11eb-9288-3e0d02f136ad.png)

In "Flat White", turning-on an option is indicated as a box with a ***bold*** check (☑️) and turning-off an option is indicated as a box with a non-bold check (Wrongly ☑️; This should be ☐).

![image](https://user-images.githubusercontent.com/42314553/103457144-e5e1f000-4d3f-11eb-93af-ce49e09d59d3.png)
 
# Environment

RStudio 1.4.869 on Windows 10 `x86_64-w64-mingw32/x64 (64-bit)`

Tools > Global Options... > (See any check-boxes)

**Comment by gadenbuie** [comment]
Thanks for the detailed report. Can you confirm that you're using the latest version of the themes? To update themes, install the latest package from GitHub, run `install_rsthemes()`, and restart RStudio.

**Comment by CLRafaelR** [comment]
I used Ver 0.1.0 (sorry for omitting the version info) when I reported the issue. After I updated the `rsthemes` to Ver. 0.2.1.9000, the problem is now all resolved. Thank you for your comment. I close this issue.
