### ISSUE TITLE
How to install just one selected theme instead of all?

### ISSUE THREAD

**Issue by GitHunter0** [gadenbuie/rsthemes#57]
The function `install_rsthemes()` installs all themes from a styles or all themes from all styles. 

Is it possible to install just one specific theme or a specified selection of themes? This would be handy and avoid extra work.

Thank you

PS: I was hoping for a package like this, so I appreciate the great work put in it.

**Comment by gadenbuie** [comment]
Thanks for the feedback! The themes are small and named to avoid conflicts with other themes. They're also all pre-built in the package, so I'm not sure that it would save any time to install only one theme at a time. I'm going to close this issue but please let me know if there's a specific need I'm not seeing.
