### ISSUE TITLE
Tabs are huge with Flat White theme

### ISSUE THREAD

**Issue by persep** [gadenbuie/rsthemes#62]
The tabs on the Flat white look too big but the other themes look ok

![image](https://user-images.githubusercontent.com/1191676/112610493-0d1afb80-8e1d-11eb-8a7f-bd08b2840387.png)

This is how it looks like with the Texmate default theme to compare:

![image](https://user-images.githubusercontent.com/1191676/112611129-b82bb500-8e1d-11eb-8dbe-45e2289ab989.png)

These are my settings

![image](https://user-images.githubusercontent.com/1191676/112610629-33409b80-8e1d-11eb-815a-4c6f3be0438e.png)

This also happens if I only install the `flat-white.rstheme` individually without `rsthemes`
I use RStudio 1.4.1103 on Windows 10.

**Comment by gadenbuie** [comment]
Yup, this is intentional. There are a couple other themes that have the large tabs as well: Night Owl and Horizon Dark.

**Comment by RaoOfPhysics** [comment]
Aww, that’s a shame, it was my favourite theme and didn’t have large tabs until a few versions ago, I think. Do you know if one can override the default tab size?

**Comment by RaoOfPhysics** [comment]
I tried reinstalling it and taking it for a spin again, but noticed that the tabs are indistinguishable from one another (except for the highlight bar on the side).

![Screenshot_20210406_154811](https://user-images.githubusercontent.com/7623019/113721470-db911280-96ef-11eb-8f46-226b8be5124c.png)

I’m running Running RStudio Version 1.4.1106 (installed via .deb) on Kubuntu 20.10.

<details><summary>Truncated sessionInfo()</summary>

```r
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10
```
</details>

**Comment by RaoOfPhysics** [comment]
> I tried reinstalling it and taking it for a spin again, but noticed that the tabs are indistinguishable from one another (except for the highlight bar on the side).

This _could_ be an issue with the KDE theming. I don’t have time to investigate at the moment, but I wanted to let you know that the issue could be only on my machine.

**Comment by RaoOfPhysics** [comment]
My issue is resolved: The _RStudio theme_ was set to “Sky” rather than “Modern”. Apologies for the noise.
