### ISSUE TITLE
Error Message: "formal argument "ui_background" matched by multiple actual arguments" when trying to use rstheme()

### ISSUE THREAD

**Issue by peterjbachman** [gadenbuie/rsthemes#67]
I'm trying to create a custom theme based around the color scheme [Mountain](https://github.com/mountain-theme/Mountain) and when I put in the following code:

```r
rsthemes::rstheme(
  theme_name = "Mountain Test", ui_background = "#0f0f0f",
  ui_background = "#f0f0f0", code_string = "#8aac8b",
  code_function = "#8f8aac", code_value = "#c6a679",
  code_message = "#ac8a8c", theme_dark = TRUE
)
```

I get the following output:

```
Error in rsthemes::rstheme(theme_name = "Mountain Test", ui_background = "#0f0f0f",  : 
  formal argument "ui_background" matched by multiple actual arguments
```

I'm not sure on how to use the `rstheme()` function and the documentation is not clear to me, so any help would be greatly appreciated since I'm new at this.

**Comment by gadenbuie** [comment]
Hi! The immediate problem is that the `ui_background` argument was repeated twice. If you take out either `ui_background = "#0f0f0f"` or `ui_background = "#f0f0f0"`, the function should run.

For a complete example using `rstheme()` you might want to check out how I used it to create the [Horizon Dark theme](https://github.com/gadenbuie/rsthemes/blob/main/inst/templates/horizon-dark.R).

I'm going to close this issue for now, but feel free to write back with any other questions or to contribute your port of the Mountain theme back to `{rsthemes}` if you want!
