### ISSUE TITLE
Vertical scroll track covers characters  

### ISSUE THREAD

**Issue by dragosmg** [gadenbuie/rsthemes#75]
Thanks again for all this functionality and for sorting out issues quickly. I hope you don't mind, but I have another one. 

The scroll track is the same colour as the background, but a different object which is in a plane in front of the text / code. In the example below it covers part of the E in `FALSE` and the closing bracket. In some scripts it's more subtle than that and sometimes it's difficult to immediately see if a parenthesis is closed without switching theme.

What do you think? Is this something worth addressing? 

Using the {rsthemes} Solarized Dark theme 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/13176361/141459893-06b5386c-5e8d-4f87-b9f3-e387d3fb67d0.png">

Using the RStudio Solarized Dark theme
<img width="305" alt="image" src="https://user-images.githubusercontent.com/13176361/141459855-782b9acd-4fdc-4335-b437-c660dd157908.png">

A similar issue is present also when selecting the appearance in _Global Options_:
{rsthemes} theme
<img width="169" alt="image" src="https://user-images.githubusercontent.com/13176361/141460260-267c774d-b854-41c5-9f61-e284d3cb9d4d.png">

RStudio theme
<img width="169" alt="image" src="https://user-images.githubusercontent.com/13176361/141460280-099fef85-1ee8-460c-bf89-e70ef3e401fa.png">

**Comment by dragosmg** [comment]
Not sure whether this is relevant, but I see the the above both on an M1 Mac (running RStudio under Rosetta2) and an Intel Mac.

**Comment by gadenbuie** [comment]
Thanks for reporting, this has been bugging me too but was a little tricky to resolve. I've fixed the general scrollbar issue in #76, so now the scrollbar background is slightly opaque

![image](https://user-images.githubusercontent.com/5420529/141490824-7545660d-c852-4047-b467-3c46f8f019f5.png)

It looks like RStudio's hiding the scrollbars in the global options panel, but fixing it isn't a big priority for me, sorry. That area tends to be full of very specialized CSS that isn't easy to maintain, so I'm okay living with it. If there's another area of the menu where's its especially painful, please let me know.

**Comment by dragosmg** [comment]
Same chunk of code as before with improve transparency:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/13176361/141494184-671922bc-505d-48e8-9b36-a13a8e03b78e.png">
🙇🏻‍♂️
