### ISSUE TITLE
API failed?

### ISSUE THREAD

**Issue by yihuanlin** [gadenbuie/rsthemes#85]
Maybe the API used have failed. 
<img width="533" alt="Screenshot 2022-05-02 at 03 29 10" src="https://user-images.githubusercontent.com/85040891/166177444-c42e1567-5b53-440e-8065-37961d863899.png">

**Comment by gadenbuie** [comment]
If it happens again, try running `rsthemes::use_theme_auto()` in your R console. That should surface the underlying error.
