### ISSUE TITLE
Night Owl Theme Issue

### ISSUE THREAD

**Issue by statsfonz** [gadenbuie/rsthemes#91]
For the Night Owl theme, it automatically checks every selection in the Global Options sections. All the code and console selections are checked and I am unable to uncheck them unless I select a different theme. This seems to only happen with the night owl rstheme but the rest seem fine. I'd like to be able to uncheck some boxes or keep the ones I already have checked like other rsthemes.

Thanks for your work on this package.

**Comment by gadenbuie** [comment]
Which version of RStudio and what operating system are you using?

**Comment by statsfonz** [comment]
I'm using Windows and I am running 2022.02.3 Build 492 version of RStudio which I believe is the latest one.

**Comment by statsfonz** [comment]
I just downloaded the night owl theme individually and it worked so maybe I had an old one. Thanks!
